language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
after_success: if [ $TRAVIS_PULL_REQUEST == 'false' ] ; then if [ $TRAVIS_BRANCH ==
  master ] ; then mvn clean deploy --settings target/travis/settings.xml; fi ; fi
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: t2+7/5EC08ES+VzbpCUsKQMyXJQzRVcskSPSKPOUV35qAlVfMTHsBEWeRakRib29KRu1lFaD2MU9hvHmfEDGLYfoJWGd0jNHdhuTjxoAwU+biHLVoo+SzZqXA06bSw3VA9sZXYPN5s3geruWgP68maDeW5h2iANA+nhVUOLH2uvzfQ7XNVTQkVl/wV20xPDbzW2Jp6M16c4dXrkCBGThCqCf7smM3SDa44SqaeJdMsQtvN2JSOndeA2575FmofjJ4CNA6JTptQiwfhXlJcPbvrVt8/QMNtA3Y2L/4hHGE052Gy+fJxY1BMqi1t8uELe5BVCe1pdLivcQiv6zWZ65jnRtIvLHy3i3VOSNk2iy1Ce4N+zXhtC4aE8yW0TO6NeeKjeljKRfMrui5bQdPjf9NDtfpIL67ffA8XPMjAbl64EFazt4nrmvYNnnrADQFXsvz2iJLBoo0RrcTGYYAeATNmvgydhVNw5eRl/tpzSPIEgzNVroKPYtZ0iknItcmDkUYEM+KWeOxNgdeteC1iAa8eWi1lCyXsyXC4cJc26XmFu8eTv8+CxO/gAPeLMxyh9WuvWNx928zzon0I0sLK3Doky9qlr+PfxeqfXvVjdY/wmosfQ50vOSv/PeuvJ/r0MiCeAT5qARGBcMvFboL/tTGZ5weK8Q7ZmvgXRj+KhaCSc=
  - secure: Bfwhju5RI5nbYf7eK9x4htv0FjyKa5B7k7SM//FqJpy3BDDaRUrAZusgAn6qUYwrh/ANpsjhnMN07hVrI8DzZOq0KR8Anj/LRjCS7QzRe+Zipn1PVv4Kc/EiOHREzieqExCiNETH/ZnMUa+qB2CG7VNbVwbZ6F+6GoBf1UK2soz8eW3ZJvqum2lSRQpRVggcKA4UnsGmxIKfQenWATtwMELpfFYhqoLipErUu6I69PdJPfywyNb8LOzyOVTaOkRTG/iv3wwxOPxSaOOJpJUmfIG8n39mVfYAtvIdJTwgW2ZVMC7/BIB4J3dFEMAYQEAlMgF94H/I0jyFbxstOqOGME0m4/893XEt9xz9BSRt9ReGZwvXI9E0wFHXD61gbVr6JpGocjGHiSpxkcnHpw1qejoYDDn+OKPSkWBsv9Mp29+AXJ7Tt6dEPwG5v+EI6EwRyVpx+EUmd5NRRiHVriFu0b09YbsLfsgSePteKUiHlbZxbG1InE7MLTljYSA+1ybyFyDtqV4FLMPVUkz5NKLFNZSg4qmfCaQQDNPKPUnrBBlOdFEth68DpPhI5ZjZwvjVbClwqsbZskK2+AlX/C9UEl0ARQJyS+eBYcZtY2w9kCGrjuOwJ+K9eYwP6yykRlZfkukY/gHHOqwMtopiHpBwnsdwf+FqNIe306K1gKNXqjk=
