language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
after_success: if [ $TRAVIS_PULL_REQUEST == 'false' ] ; then if [ $TRAVIS_BRANCH ==
  master ] ; then mvn clean deploy --settings target/travis/settings.xml; fi ; fi
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
dd:
  secure: Lypp9Up3RtWpyRNTqO5fvfJfo0nqgxAHY6TwQchzV0fqz4cKsA2lO3GcjOaDRaUBUTu34Rn6UYgjR9cqrQLg6g+g1tMmW6ic5AduYSCCilfnHuymfJ5xANBeWe4DOHi+x2D/1gwaFZgQLY2uOM/yUnLFt48nghvRSH1HcZJJIqsnbqyDsZdj5F+b2JoIH6WRBXpPYZHl1dsFNY7w8lKcNEmJBvmwtPsQFAZ1VeLmm3BhxRwDQae32gz/zkJPawOmF+pQrvZbD4fYgg5j9bLayVSvKn1FZTpxC6vX3CldWb4A8l7IUEd/ezl53hCGLT+3tFMN1GZGhyTrYHEvN9+IxtC6VKGc8VXyaeFccox/Jiss3MbBFJ6A2IlaDQhp0Ia7F1SFZIScONRxYvqQcQ2WRrlaLnjFW+ZyAsTyWQ3hq7LrIOKFw7OMz81s5voigjR0ta0PxfSQ0EeoqNgLdRmDss1LU0B//HubLGgHYkhLX9fvwuJk30JbVmHa66Y3w6A0UkLkj5eHDIotA1Q0mbL5F/Yib3zf9W3qqraahVH9czvZJHgcXfP5RjDIg4YcjUDT6mmjaUSVATUTTtISoTV0MbcuTXUBC5Wynn03stmHBjgdUEme1LEuwoyzZ0Kfj4OhvPtCWVhfib0zInSmd5buRwmxKa8URjmv0BIKi09kHoo=
