language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: 
  - git clone -b travis `git config --get remote.origin.url` target/travis
  - mvn dependency:resolve -DoverWriteSnapshots=true
after_success: mvn clean deploy --settings target/travis/settings.xml -DskipTests=true
branches:
  only:
  - master
  - release
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: XvH15v94SO0Js+GyOYKvHKmZ3+z69upabtmf+wFd/lGjm9gSe7/cMAWWPIZc8mzxd0K9+Nd3Ds+OsyDEdn5Z/F8v9kqQfY5loK/2sLaIoWW0zOpMdygPE6JSCWsH58uTGCgeVLAG1Ucf1QEVWZSYZFNvqfP3Fr4aCv3wKPc9Rb/eWl+7TEObWAbA0D8LiTQ7XrfnnkH8nhRlyxWTJ8xWdfSegFCcG5TCSmFVDgYD5NDXcY5vWp+jUYmrCqL/oKHQJFqfFIWG7uU0YliF7qxzNPDasjHY5l0r0vfzSSrqwBpdici/ZyPpVfN4ygTfBC5FnY7qTVi4Xm+oAYi7nvmFL8JO+JI0RhfxpoxRLySFLWecB3qZzbmJO608W6vsBFc1p9UrcP3K7HPWTEijvYcgmltGQpzL4uMk8AYkRBfHQ9nE9/jKH2OedJFe5Ewf2gQSI4uJVaUK6OfelNVoI+MnCi4Bv8CJaOIaOEEOkVOVzAUu9ds3mjZKrloicjYeALn47GkEOfe+wS6ugUMs2brS94nrup+YriT2rxegyPHGWRgg3VWOGUHBxBKswJR7VBdQpAs0zgZE6w4s4h3Du7PHNExiU5v9rs3wisJzyNL7K0A4yNtdtfTJGFSYCv8zTip17n4quwOX5J0E9uAT9WK7DTGk0AJkJyjOibx53m/mfZE=
  - secure: WRZA7jxS8o1AsXks4mY8NRb0P5XXvp2FWQ7NmyvwP1VF9KjbGX9EuKvgbJB1aEzpaSVpZhtQpVv2wXIAwnc7yCBsg6PhF42VYeBa2jxKTJ76z6lR5Bapba4EBjRPatqRIjFygt4MmPeYwcSKjMGv7G+mVtq2aSW86L3XCK92WAXn3B8XVED5+lLaTx4YT8p+9qe4VNrLyKXvMuOZDktRmzHXzk8i6DPbdqjxmzU2g+/f+kV+ZwNPD6TQ6qUyltpRiTRHHRCih9k61jp60fmjTrTfRI034alumMUjeF+tSiw8veGeV2p3qC7UB9Qg79TS5rzUHJ8D2/DQ39JZFrNcmvYUfONtrwfhTdd3GuWC8ma9LJ09Nl7Tb+D26GtqmoQT2KvopQyySmFw6Dha23PsJTkeZomyVVwO2PYBOq8VJCVyV5Pf/LvKaxr51aRXIS+/o3IsI+Dm02R2CLPROUPnTNpQGHzxKBiAp+u4+WR3rBoH5M1NnPUSMmIAzhIPPTGlNpdGKV+VH4Nv5dt5qDXjtm96CV/6YJKnVkouKXlDJgUA5VLYs/fz8JiA0fkfGZm9zP6m53mdV1BVrv5X32shkOdiO2hvUbOMmgu+TMvJHUnb27Atss+Ffwiqk2i3LR0UlawtEf6UYMJpAq51ybLg6EDAgWce2gwogbjoY+Vhy+0=
