language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "if [ $TRAVIS_PULL_REQUEST == 'false' ] ; then if [ $TRAVIS_BRANCH == release ] ; then mvn clean deploy --settings target/travis/settings.xml; fi ; fi"
branches:
  only:
  - master
  - release
notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always
env:
  global:
  - secure: JixSWEh3WG6azS1xO1K22NzmYvrTy+4o5OkwlyBZSjrbGbx6tlT31JzaFxFCyPP5qewT9q9uIPkcBuC3j2heIB2gQDvMX/8OE6RJbWMmbXiWX697naUEJYu94X+5ncHbFHEXBUnwRizAxootYD+EKfFB0opAbUVcFxaHU+HspQrIAp3ntZsWjBii5pkgqlnoE92yicyudx+ZBRwa67mjDfLEMRnFhc19Fo2DiFv5lNp4DssCfocF46BKaKu1+2qpqSZgt5oAXzEkbkU8/BcO+Bd3FMVAg85sZoAi2XdR6OEPNQzi1VwrgfVcYl4yv3nR6sIk2uxIrRvxPaVs0SI4jd90VyVEGPjXbezZ/zvPlHirNesYCu/Mz1GVCBGajJDWELo3ElMRIH6R+hHjQ2V3PxxaPFqqGXlEmIuBKPL0nk61gr/3OzyFKyMyL3Rnj67pcsQ+NWTJzLSA4JLfC2TkRcx0DmZNIjnAsUEZnybXCaOEhpFksrJz7d0PwBX1RRT/RSqYR0YLbgLBfiezus4QlISVAFu929ema0I6hSj/Lf60R027hoWhqQ8GZs+W9qxMvugBIDf+hHBPP6IPVJPPQosdxvRO7anmL9onhlUQKne6Jkd8uzrZr1q9CM7mk2tcKW34sBvSdIz8gEWdrRzsDQovaWq14ew/ROuovuJpjmQ=
  - secure: UZklSPCoy2NflSIrgXGfWo8UIqytUCRFLHQxX1jMloEj/paXyyxSI0X43gZ5howIVh0MS+p+m5+LQJHu8ew+50pyUMoOby0+3fllweW8H0RofxgWIq+13MbJYBOqduhAqv+1N2CtYgoUnkUxPCiu03Cl7NfqeH4OcRb+802u2u06Fi1le5qmLzhPT7p8SgsgWV8GA5VDOJ1gyOv54NmnYkxPTKn0VYmV/jaPso6kZwD4iDl+sAqiDfr1b4NbndpPTvnkcyIP9iBXXmnS4J2NT5sGDh7yp0QRccvfnArazUrGyyI7ZQcEJflZbb01rQjgbkl8nHltKplzwsfTnSfvFSTDG6vVVJwMyYuQLJwqv3XDo9hyd66OG5NpRTSiz6q7mwAIMIvqLhPEIUh504+7d7odFa5qQ4u6O6KDCZg+zjsYgN1/ZKTLzwXlMBMUuI0aeFRJj6Nod97DUxbFkcH/JQ1qR+m8WozonXkKyVzlK5IueZ1+7LhA+aG0yLj/JAYyu1Ue21E7E2o9nUyQLMLsaD33cfjPhr9gWSnURetMBgF9V4Lqn5TFGno8TzWDKVS5XOG7BPwzAy6Uxw/MNRlHJw4JL0JJxPT+mW8yzDUsMwWNkdAmFRV2fZWs9XUdD+d4UJngmSt8SO9OwEJjD39LNPMZ0jRteaySl5cw0/RUmlQ=
